### ISSUE TITLE
`vcf_melt` script is incompatible with recent python

### ISSUE THREAD

**Issue by dfornika** [dfornika/ncov-db#1]
The [`vcf_melt`](https://github.com/dfornika/ncov-db/blob/main/scripts/vcf_melt) script in this repo is adapted from the [`vcf_melt`](https://github.com/jamescasbon/PyVCF/blob/master/scripts/vcf_melt) script from [PyVCF](https://github.com/jamescasbon/PyVCF). 

There seems to be some incompatibilities between PyVCF and python > v3.5 that cause installation of this package to fail when following the installation instructions in the README.

Either limit the compatibility of ncov-db to python <= 3.5, or find an alternative VCF parsing library.

**Comment by dfornika** [comment]
[vcflib](https://github.com/vcflib/vcflib) includes an example [python script for loading a VCF into SQLite](https://github.com/vcflib/vcflib/blob/master/scripts/vcf2sqlite.py), but it only appears to parse the following fields from the VCF: `CHROM`, `POS`, `ID`, `REF`, `ALT`, `QUAL`, `FILTER`.

**Comment by dfornika** [comment]
It may make more sense to move the vcf_melt script into a separate repo. That would eliminate the need to list it as a dependency of the `ncov-db` package.

**Comment by cdfjell** [comment]
I get error when installing ncov-db from pip that may be related. When I install pyvcf using conda (and not pip), pip installs ncov-db properly. Maybe that is the case with vcf_melt - I will have a look

**Comment by dfornika** [comment]
I've gone ahead and factored the `vcf_melt` script into a [separate repo](https://github.com/dfornika/vcf-melt), so this codebase no longer depends on pyvcf.
